from enum import IntEnum


class ExitCode(IntEnum):
    OK = 0
    INVALID_INPUT = 1
    UNSUPPORTED_MANIFEST = 2
    INSPECTION_FAILED = 3
    INCOMPLETE = 4
    TOOL_UNAVAILABLE = 5
    RESOLUTION_FAILED = 6
    PLAN_REJECTED = 7
    LOCK_FAILED = 8
    APPLY_FAILED = 9
    VERIFICATION_FAILED = 10
    PROMOTION_FAILED = 11
    ROLLBACK_FAILED = 12
    MAINTENANCE_FAILED = 13
